feat : 기본 Repository 생성 #24 해결
nsnnsn12/pr2s pull request #30
Opened 2022-06-26 11:33 UTC by HyunWooParkKEIG

## 연관된 Issue Number
#24

### 반영 브랜치
- feature/24 -> develop

### 변경사항
- 각 테이블 Entity 별로 Repository 생성

### 테스트
- 스프링 부트 실행

### Issue 해결 여부(해결 or TODO)
- 해결

2022-06-26 11:45 UTC, nsnnsn12 commented
주석 좀 달아주세요

2022-06-26 13:44 UTC, nsnnsn12 requested changes
주석이 안 달려 있습니다

2022-06-26 23:47 UTC, HyunWooParkKEIG commented
주석 추가했습니다

2022-06-27 03:37 UTC, nsnnsn12 commented on src/main/java/com/metacrew/pr2s/repository/AddressRepository.java
> + * 주소를 수정 및 조회할 수 있다.
이 부분은 주석 제거하는게 좋을 것 같습니다

2022-06-30 22:23 UTC, HyunWooParkKEIG commented
전체 Repository 주석 수정 했습니다

2022-07-01 10:40 UTC, merged