REFACTOR : 기관 수정 기능 예외 처리 추가 및 필수 파라미터 반영
nsnnsn12/pr2s pull request #61
Opened 2022-07-16 13:08 UTC by HyunWooParkKEIG

## 연관된 Issue Number
#52

### 반영 브랜치
ex) feature/52 -> develop

### 변경사항
- 기관 수정 기능 예외처리 및 필수 파라미터 반영했습니다

### 테스트
- 스프링 부트 테스트

### Issue 해결 여부(해결 or TODO)
- TODO

2022-07-18 14:15 UTC, nsnnsn12 requested changes
제가 단 코멘트 확인 후 수정 부탁드립니다

2022-07-18 14:15 UTC, nsnnsn12 commented on src/main/java/com/metacrew/pr2s/dto/InstitutionDto.java
> -    private Boolean isApprovedRegistration;
InstitutionDto가 등록할 때만 필요하다면 boolean이 필요없겠지만 
dto가 다른 용도로도 사용된다면 해당 정보가 필요하다 생각합니다.
그리고 등록할 때만 사용하는 용도라면 dto이름을 바꾸어주어야 할 것 같습니다

2022-07-18 14:15 UTC, nsnnsn12 commented on src/main/java/com/metacrew/pr2s/entity/Institution.java
> +    public void updateInstitution(InstitutionDto institutionDto, Workdays workdays, Address address) {
Workday나 Address는 이미 테이블로 관리되고 있기 때문에 Workday, Address 자체를 변경해야 하지 않을까요?

2022-07-18 14:15 UTC, nsnnsn12 commented on src/main/java/com/metacrew/pr2s/service/institutionservice/InstitutionManagerService.java
> +        Workdays workdays = Workdays.createWorkdays(workdaysDto);
이 부분에서 바로 workday를 수정하면 updateInstitution 메소드에서 Workdays를 받지 않아도 될 것 같습니다.

2022-07-18 14:15 UTC, nsnnsn12 commented on src/main/java/com/metacrew/pr2s/service/institutionservice/InstitutionManagerService.java
> +        Address address = Address.createAddressByAddressDto(addressDto);
위에 코멘트와 동일합니다.

2022-07-18 14:15 UTC, nsnnsn12 commented on src/main/java/com/metacrew/pr2s/service/institutionservice/InstitutionManagerService.java
> +        validateInstitution(institutionDto, workdaysDto, addressDto);
dto 파라미터에 대한 유효성 검사는 컨트롤러에서 한다고 생각해야 할 것 같습니다

2022-07-18 14:15 UTC, nsnnsn12 commented on src/main/java/com/metacrew/pr2s/service/institutionservice/InstitutionManagerService.java
> +    public void validateInstitution(InstitutionDto institutionDto, WorkdaysDto workdaysDto, AddressDto addressDto) {
dto 파라미터에 대한 유효성 검사는 컨트롤러에서 한다고 생각해야 할 것 같습니다

2022-07-22 10:01 UTC, HyunWooParkKEIG commented
유효성 검사 부분은 추후에 생길 경우를 대비해서 남겨두었습니다.

2022-07-22 12:14 UTC, nsnnsn12 approved these changes, later dismissed

2022-07-22 12:26 UTC, nsnnsn12 commented on src/main/java/com/metacrew/pr2s/dto/InstitutionCreateDto.java
> +public class InstitutionCreateDto {
주석 수정 필요

2022-07-22 12:27 UTC, nsnnsn12 commented on src/main/java/com/metacrew/pr2s/dto/InstitutionCreateDto.java
> +    public InstitutionCreateDto(Institution institution) {
사용자에게 보여 주기 위해 dto를 사용하는 것인데 해당 dto가 사용자에게 필요한 정보를 제공하는지 생각해봐야 할 듯

2022-07-23 04:24 UTC, nsnnsn12 approved these changes

2022-07-23 04:24 UTC, merged